# Generated by Django 5.2.14 on 2026-08-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google OAuth orqali kirgan foydalanuvchi ID si.', max_length=64, null=True, unique=True, verbose_name='Google ID'),
        ),
    ]
