# Generated by Django 5.2.14 on 2026-08-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role_parentstudentlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', help_text='Tizim interfeysi tili.', max_length=5, verbose_name='til'),
        ),
    ]
