# Generated by Django 5.2.14 on 2026-09-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bot',
            field=models.BooleanField(default=False, help_text="Sun'iy AI raqib (Arena bot) hisobi. Real foydalanuvchi emas.", verbose_name='botmi'),
        ),
    ]
