# Generated by Django 5.2.14 on 2026-08-23 13:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nomi')),
                ('badge_type', models.CharField(choices=[('imlo_master', 'Imlo Ustasi'), ('gazal_scholar', "G'azal Bilimdon"), ('lugat_academic', "Lug'at Akademigi"), ('speed_demon', 'Tezlik Shaytoni'), ('combo_king', 'Combo Qirol'), ('perfect_game', "Mukammal O'yinchi"), ('daily_player', "Kunlik O'yinchi"), ('xp_hunter', 'XP Ovchisi'), ('coin_collector', "Tangalar Yig'uvchi"), ('grandmaster', 'Grandmaster')], max_length=30, unique=True, verbose_name='nishon turi')),
                ('description', models.TextField(verbose_name='tavsif')),
                ('icon_emoji', models.CharField(default='🏅', max_length=10, verbose_name='emoji')),
                ('required_value', models.PositiveIntegerField(default=1, help_text="Badge olish uchun kerakli minimal ko'rsatkich (masalan, 50 ta to'g'ri javob).", verbose_name='kerakli qiymat')),
                ('xp_bonus', models.PositiveIntegerField(default=50, help_text='Badge olganda beriladigan bonus XP.', verbose_name='bonus XP')),
            ],
            options={
                'verbose_name': 'Nishon',
                'verbose_name_plural': 'Nishonlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nomi')),
                ('slug', models.SlugField(choices=[('imlo_mina', 'Imlo Minalari'), ('gazal_puzzle', 'Navoiy vs Dunyo'), ('lugat_match', "Eski So'zlar Dueli")], unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='tavsif')),
                ('icon_emoji', models.CharField(default='🎮', help_text="Game kartochkasida ko'rsatiladigan emoji.", max_length=10, verbose_name='ikonka emoji')),
                ('xp_per_correct', models.PositiveIntegerField(default=10, verbose_name="XP (to'g'ri javob uchun)")),
                ('coins_per_correct', models.PositiveIntegerField(default=5, verbose_name="Coins (to'g'ri javob uchun)")),
                ('combo_multiplier', models.DecimalField(decimal_places=1, default=1.5, help_text="Ketma-ket to'g'ri javoblar uchun bonus multiplier.", max_digits=3, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='Combo koeffitsienti')),
                ('is_active', models.BooleanField(default=True, verbose_name='faolmi')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
            ],
            options={
                'verbose_name': "O'yin",
                'verbose_name_plural': "O'yinlar",
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GameLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='sarlavha')),
                ('difficulty', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='qiyinlik (1-10)')),
                ('question_data', models.JSONField(default=dict, help_text="O'yin turiga qarab JSON formatdagi savol/level ma'lumoti.", verbose_name="savol ma'lumoti (JSON)")),
                ('hint', models.TextField(blank=True, verbose_name='maslahat')),
                ('time_limit_seconds', models.PositiveIntegerField(default=60, verbose_name='vaqt cheklovi (soniya)')),
                ('xp_reward', models.PositiveIntegerField(default=10, verbose_name='XP mukofoti')),
                ('is_active', models.BooleanField(default=True, verbose_name='faolmi')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='games.game', verbose_name="o'yin")),
            ],
            options={
                'verbose_name': "O'yin leveli",
                'verbose_name_plural': "O'yin levellari",
                'ordering': ['game', 'sort_order'],
                'indexes': [models.Index(fields=['game', 'difficulty'], name='idx_level_game_diff')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='erishilgan sana')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='games.badge', verbose_name='nishon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi nishoni',
                'verbose_name_plural': 'Foydalanuvchi nishonlari',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserGameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.PositiveIntegerField(default=0, verbose_name='umumiy XP')),
                ('total_coins', models.PositiveIntegerField(default=0, verbose_name='umumiy coins')),
                ('games_played', models.PositiveIntegerField(default=0, verbose_name="o'ynalgan o'yinlar")),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name="to'g'ri javoblar")),
                ('wrong_answers', models.PositiveIntegerField(default=0, verbose_name="noto'g'ri javoblar")),
                ('best_streak', models.PositiveIntegerField(default=0, help_text="Ketma-ket to'g'ri javoblar eng uzun zanjiri.", verbose_name='eng yaxshi streak')),
                ('best_time_seconds', models.PositiveIntegerField(default=0, verbose_name='eng yaxshi vaqt (soniya)')),
                ('high_score', models.PositiveIntegerField(default=0, verbose_name='eng yuqori ball')),
                ('last_played_at', models.DateTimeField(blank=True, null=True, verbose_name="oxirgi o'ynalgan")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scores', to='games.game', verbose_name="o'yin")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': "O'yin natijasi",
                'verbose_name_plural': "O'yin natijalari",
                'ordering': ['-total_xp'],
                'indexes': [models.Index(fields=['user'], name='idx_score_user'), models.Index(fields=['-total_xp'], name='idx_score_xp')],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
