# Generated by Django 5.2.14 on 2026-08-26 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_usergamescore_idx_score_user_game_xp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='sarlavha')),
                ('description', models.TextField(verbose_name='tavsif')),
                ('challenge_type', models.CharField(choices=[('test_count', 'N ta test topshir'), ('essay_count', 'N ta esse yoz'), ('game_xp', "N XP to'pla"), ('perfect_score', '100% ball oling'), ('streak', 'N kun ketma-ket kiring')], max_length=30, verbose_name='challenge turi')),
                ('target_value', models.PositiveIntegerField(default=5, verbose_name='maqsadli qiymat')),
                ('xp_reward', models.PositiveIntegerField(default=100, verbose_name='XP mukofoti')),
                ('coin_reward', models.PositiveIntegerField(default=50, verbose_name='Tanga mukofoti')),
                ('starts_at', models.DateTimeField(verbose_name='boshlanish vaqti')),
                ('ends_at', models.DateTimeField(verbose_name='tugash vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
            ],
            options={
                'verbose_name': 'Haftalik challenge',
                'verbose_name_plural': "Haftalik challenge'lar",
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='joriy streak')),
                ('best_streak', models.PositiveIntegerField(default=0, verbose_name='eng uzun streak')),
                ('last_login_date', models.DateField(blank=True, null=True, verbose_name='oxirgi kirish sanasi')),
                ('total_logins', models.PositiveIntegerField(default=0, verbose_name='jami kirishlar')),
                ('reward_3claimed', models.BooleanField(default=False)),
                ('reward_7claimed', models.BooleanField(default=False)),
                ('reward_14claimed', models.BooleanField(default=False)),
                ('reward_30claimed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_streak', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kunlik streak',
                'verbose_name_plural': 'Kunlik streaklar',
            },
        ),
        migrations.CreateModel(
            name='UserChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.PositiveIntegerField(default=0, verbose_name='joriy qiymat')),
                ('is_completed', models.BooleanField(default=False, verbose_name='tugallanganmi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='tugallangan vaqt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='games.weeklychallenge', verbose_name='challenge')),
            ],
            options={
                'verbose_name': 'Challenge progressi',
                'verbose_name_plural': 'Challenge progresslari',
                'ordering': ['-current_value'],
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
