# Generated by Django 5.2.14 on 2026-09-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_weeklychallenge_dailystreak_userchallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('imlo_master', 'Imlo Ustasi'), ('gazal_scholar', "G'azal Bilimdon"), ('lugat_academic', "Lug'at Akademigi"), ('speed_demon', 'Tezlik Shaytoni'), ('combo_king', 'Combo Qirol'), ('perfect_game', "Mukammal O'yinchi"), ('daily_player', "Kunlik O'yinchi"), ('xp_hunter', 'XP Ovchisi'), ('coin_collector', "Tangalar Yig'uvchi"), ('grandmaster', 'Grandmaster'), ('duel_winner_10', "10 G'alaba Streak"), ('night_owl', 'Tungi Boyqush'), ('essay_master', 'Esse Ustasi'), ('arena_elite', 'Arena Elitasi')], max_length=30, unique=True, verbose_name='nishon turi'),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(choices=[('imlo_mina', 'Imlo Minalari'), ('gazal_puzzle', 'Navoiy vs Dunyo'), ('lugat_match', "Eski So'zlar Dueli"), ('arena_duel', 'Quiz Arena Dueli'), ('telegram_quiz', 'Telegram Quiz')], unique=True, verbose_name='slug'),
        ),
    ]
