# Generated by Django 5.2.14 on 2026-08-23 07:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nomi')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('icon', models.CharField(blank=True, help_text='Bootstrap Icons yoki boshqa CSS klass nomi.', max_length=50, verbose_name='ikonka (CSS class)')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.category', verbose_name='ota kategoriya')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='tavsif')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/thumbnails/%Y/%m/', verbose_name='kichik rasm')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Nashr etilgan'), ('archived', 'Arxivlangan')], default='draft', max_length=20, verbose_name='holat')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='narx')),
                ('max_students', models.PositiveIntegerField(blank=True, help_text="Cheksiz bo'lsa, bo'sh qoldiring.", null=True, verbose_name="maksimal o'quvchilar soni")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.category', verbose_name='kategoriya')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_taught', to=settings.AUTH_USER_MODEL, verbose_name="o'qituvchi")),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='yozilgan sana')),
                ('is_completed', models.BooleanField(default=False, verbose_name='tugatilgan')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='kurs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name="o'quvchi")),
            ],
            options={
                'verbose_name': 'Yozilish',
                'verbose_name_plural': 'Yozilishlar',
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='courses_enrolled', through='courses.Enrollment', to=settings.AUTH_USER_MODEL, verbose_name="yozilgan o'quvchilar"),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='tartib raqami')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course', verbose_name='kurs')),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modullar',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='sarlavha')),
                ('content_type', models.CharField(choices=[('text', 'Matn'), ('video', 'Video'), ('file', 'Fayl')], default='text', max_length=10, verbose_name='kontent turi')),
                ('content_body', models.TextField(blank=True, verbose_name='matn kontenti')),
                ('content_url', models.URLField(blank=True, help_text='Video embed URL yoki tashqi havola.', verbose_name='video/link URL')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='lessons/attachments/%Y/%m/', verbose_name='ilova fayl')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='tartib raqami')),
                ('is_free', models.BooleanField(default=False, help_text="Ro'yxatdan o'tmasdan ko'rishga ruxsat.", verbose_name="bepul ko'rish mumkinmi")),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.module', verbose_name='modul')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='idx_course_status'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['teacher'], name='idx_course_teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('module', 'title')},
        ),
    ]
