# Generated by Django 5.2.14 on 2026-08-29 14:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nomi')),
                ('plan_type', models.CharField(choices=[('free', 'Bepul'), ('premium', 'Premium'), ('family', 'Oila')], max_length=20, unique=True, verbose_name='reja turi')),
                ('description', models.TextField(verbose_name='tavsif')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='narx (oylik)')),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='narx (yillik)')),
                ('max_tests_per_day', models.PositiveIntegerField(default=5, help_text='0 = cheksiz', verbose_name='maksimal testlar (kuniga)')),
                ('max_essays_per_week', models.PositiveIntegerField(default=2, help_text='0 = cheksiz', verbose_name='maksimal esselar (haftasiga)')),
                ('max_ai_grading', models.BooleanField(default=True, verbose_name='AI baholash')),
                ('detailed_analytics', models.BooleanField(default=False, verbose_name='batafsil tahlil')),
                ('pdf_certificate', models.BooleanField(default=False, verbose_name='PDF sertifikat')),
                ('priority_support', models.BooleanField(default=False, verbose_name="ustuvor qo'llab-quvvatlash")),
                ('unlimited_tests', models.BooleanField(default=False, verbose_name='cheksiz testlar')),
                ('unlimited_essays', models.BooleanField(default=False, verbose_name='cheksiz esselar')),
                ('is_active', models.BooleanField(default=True, verbose_name='faolmi')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
            ],
            options={
                'verbose_name': 'Obuna rejası',
                'verbose_name_plural': 'Obuna rejaları',
                'ordering': ['sort_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='summa')),
                ('currency', models.CharField(default='UZS', max_length=3, verbose_name='valyuta')),
                ('payment_method', models.CharField(max_length=50, verbose_name="to'lov usuli")),
                ('payment_id', models.CharField(blank=True, max_length=200, verbose_name="to'lov ID")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('completed', 'Tugallangan'), ('failed', 'Xatolik'), ('refunded', 'Qaytarilgan')], default='pending', max_length=20, verbose_name='holat')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='tugallangan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.subscriptionplan', verbose_name='reja')),
            ],
            options={
                'verbose_name': "To'lov tarixi",
                'verbose_name_plural': "To'lov tarixlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('expired', 'Muddati tugagan'), ('cancelled', 'Bekor qilingan'), ('trial', 'Sinov muddati')], default='active', max_length=20, verbose_name='holat')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='boshlangan')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='tugash vaqti')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='bekor qilingan')),
                ('payment_id', models.CharField(blank=True, help_text="To'lov tizimidagi ID", max_length=200, verbose_name="to'lov ID")),
                ('payment_method', models.CharField(blank=True, choices=[('click', 'Click'), ('payme', 'Payme'), ('uzcard', 'UzCard'), ('stripe', 'Stripe'), ('free', 'Bepul')], max_length=50, verbose_name="to'lov usuli")),
                ('is_trial', models.BooleanField(default=False, verbose_name='sinov muddatimi')),
                ('trial_days', models.PositiveIntegerField(default=7, verbose_name='sinov kunlari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.subscriptionplan', verbose_name='reja')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi obunasi',
                'verbose_name_plural': 'Foydalanuvchi obunalari',
            },
        ),
    ]
