# Generated by Django 5.2.14 on 2026-08-30 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Admin tomonidan qoldirilgan izoh', verbose_name='admin izohi'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payments', to=settings.AUTH_USER_MODEL, verbose_name='tekshirgan admin'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='screenshot_file_id',
            field=models.CharField(blank=True, help_text="Telegram'dan olingan rasm file_id", max_length=255, verbose_name='screenshot file_id'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='telegram_message_id',
            field=models.BigIntegerField(blank=True, help_text='Screenshot yuborilgan Telegram xabar ID', null=True, verbose_name='Telegram xabar ID'),
        ),
    ]
