# Generated by Django 5.2.14 on 2026-09-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paymentrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Bepul'), ('starter', 'Starter'), ('pro', 'Pro'), ('premium', 'Premium'), ('family', 'Oila')], max_length=20, unique=True, verbose_name='reja turi'),
        ),
    ]
