# Generated by Django 5.2.14 on 2026-09-04 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arena', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arenaplayer',
            name='best_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='eng yaxshi kombo'),
        ),
        migrations.AddField(
            model_name='arenaplayer',
            name='channel_name',
            field=models.CharField(blank=True, default='', help_text='Foydalanuvchining WebSocket kanali — jonli xabarlar uchun.', max_length=200, verbose_name='kanal nomi'),
        ),
        migrations.AddField(
            model_name='arenaplayer',
            name='coins_earned',
            field=models.PositiveIntegerField(default=0, verbose_name='olgan tangalar'),
        ),
        migrations.AddField(
            model_name='arenaplayer',
            name='is_bot',
            field=models.BooleanField(default=False, verbose_name='botmi'),
        ),
        migrations.AddField(
            model_name='arenaplayer',
            name='rating_before',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='dueldan oldingi ELO'),
        ),
        migrations.AddField(
            model_name='arenaplayer',
            name='rating_change',
            field=models.IntegerField(default=0, verbose_name="ELO o'zgarishi"),
        ),
        migrations.AddField(
            model_name='arenaplayer',
            name='streak',
            field=models.PositiveIntegerField(default=0, verbose_name='joriy kombo'),
        ),
        migrations.AddField(
            model_name='arenaplayer',
            name='total_time_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Barcha javoblarga ketgan umumiy vaqt — tezlik statistikasi.', verbose_name='jami javob vaqti (soniya)'),
        ),
        migrations.AddField(
            model_name='arenaplayer',
            name='xp_earned',
            field=models.PositiveIntegerField(default=0, verbose_name='olgan XP'),
        ),
        migrations.AddField(
            model_name='arenaroom',
            name='bot_user',
            field=models.ForeignKey(blank=True, help_text="BOT rejimida ishlatiladigan sun'iy raqib hisobi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arena_bot_rooms', to=settings.AUTH_USER_MODEL, verbose_name='bot hisob'),
        ),
        migrations.AddField(
            model_name='arenaroom',
            name='mode',
            field=models.CharField(choices=[('queue', 'Navbat'), ('custom', 'Shaxsiy xona'), ('bot', 'Bot bilan')], default='queue', max_length=10, verbose_name='rejim'),
        ),
        migrations.AddField(
            model_name='arenaroom',
            name='p1_rating_before',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="1-o'yinchi ELO"),
        ),
        migrations.AddField(
            model_name='arenaroom',
            name='p1_rating_change',
            field=models.IntegerField(default=0, verbose_name="1-o'yinchi ELO o'zgarishi"),
        ),
        migrations.AddField(
            model_name='arenaroom',
            name='p2_rating_before',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="2-o'yinchi ELO"),
        ),
        migrations.AddField(
            model_name='arenaroom',
            name='p2_rating_change',
            field=models.IntegerField(default=0, verbose_name="2-o'yinchi ELO o'zgarishi"),
        ),
        migrations.AddField(
            model_name='arenaroom',
            name='question_started_at',
            field=models.DateTimeField(blank=True, help_text='Joriy savol yuborilgan vaqt — tezlik bonusi hisoblash uchun.', null=True, verbose_name='savol boshlangan'),
        ),
        migrations.CreateModel(
            name='ArenaAnswerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='savol tartibi')),
                ('answer', models.CharField(max_length=1, verbose_name='javob')),
                ('is_correct', models.BooleanField(default=False, verbose_name="to'g'rimi")),
                ('time_taken_seconds', models.FloatField(default=0.0, verbose_name='javob vaqti (soniya)')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='ball')),
                ('base_points', models.PositiveIntegerField(default=0, verbose_name='asosiy ball')),
                ('combo_bonus', models.PositiveIntegerField(default=0, verbose_name='kombo bonusi')),
                ('time_bonus', models.PositiveIntegerField(default=0, verbose_name='tezlik bonusi')),
                ('streak', models.PositiveIntegerField(default=0, verbose_name='joriy kombo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_logs', to='arena.arenaplayer', verbose_name="o'yinchi")),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_logs', to='arena.arenaroom', verbose_name='xona')),
            ],
            options={
                'verbose_name': 'Arena javobi',
                'verbose_name_plural': 'Arena javoblari',
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('player', 'position'), name='uq_arena_answer_player_position')],
            },
        ),
        migrations.CreateModel(
            name='ArenaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=1000, verbose_name='ELO reyting')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name="g'alabalar")),
                ('losses', models.PositiveIntegerField(default=0, verbose_name="mag'lubiyatlar")),
                ('draws', models.PositiveIntegerField(default=0, verbose_name='duranglar')),
                ('duels_played', models.PositiveIntegerField(default=0, verbose_name="o'ynalgan duellar")),
                ('current_win_streak', models.PositiveIntegerField(default=0, verbose_name="joriy g'alaba seriyasi")),
                ('best_win_streak', models.PositiveIntegerField(default=0, verbose_name="eng uzun g'alaba seriyasi")),
                ('total_correct', models.PositiveIntegerField(default=0, verbose_name="jami to'g'ri javoblar")),
                ('total_answers', models.PositiveIntegerField(default=0, verbose_name='jami javoblar')),
                ('total_time_seconds', models.PositiveIntegerField(default=0, verbose_name='jami javob vaqti')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arena_profile', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Arena profili',
                'verbose_name_plural': 'Arena profillari',
                'indexes': [models.Index(fields=['-rating'], name='idx_arena_rating')],
            },
        ),
        migrations.CreateModel(
            name='ArenaQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=1000, verbose_name='ELO reyting')),
                ('status', models.CharField(choices=[('waiting', 'Kutmoqda'), ('matched', 'Topildi'), ('expired', 'Bekor qilingan')], default='waiting', max_length=10, verbose_name='holat')),
                ('channel_name', models.CharField(blank=True, default='', help_text='Navbatga tushgan WebSocket kanali — match topilganda xabar yuborish uchun.', max_length=200, verbose_name='kanal nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('matched_at', models.DateTimeField(blank=True, null=True, verbose_name='topilgan')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_entries', to='arena.arenaroom', verbose_name='xona')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arena_queue_entries', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Arena navbati',
                'verbose_name_plural': 'Arena navbatlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'rating'], name='idx_queue_status_rating')],
            },
        ),
    ]
