# Generated by Django 5.2.14 on 2026-08-23 07:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='savol matni')),
                ('question_type', models.CharField(choices=[('single', "Bita to'g'ri javob"), ('multiple', "Ko'p to'g'ri javob")], default='single', max_length=10, verbose_name='savol turi')),
                ('points', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='ball')),
                ('explanation', models.TextField(blank=True, help_text="Javob topshirilgandan keyin ko'rsatiladi.", verbose_name='tushuntirish')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='tartib raqami')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='javob varianti')),
                ('is_correct', models.BooleanField(default=False, verbose_name="to'g'ri javobmi")),
                ('position', models.PositiveIntegerField(default=0, verbose_name='tartib raqami')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='tests.question', verbose_name='savol')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
                'ordering': ['position'],
                'unique_together': {('question', 'text')},
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('time_limit_minutes', models.PositiveIntegerField(default=0, help_text='0 = cheksiz vaqt.', verbose_name='vaqt cheklovi (daqiqa)')),
                ('max_attempts', models.PositiveIntegerField(default=1, help_text='0 = cheksiz urinishlar.', verbose_name='maksimal urinishlar')),
                ('pass_percentage', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="o'tish foizi (%)")),
                ('difficulty', models.CharField(choices=[('easy', 'Oson'), ('medium', "O'rta"), ('hard', 'Qiyin')], default='medium', max_length=10, verbose_name='qiyinlik darajasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='faolmi')),
                ('show_results_immediately', models.BooleanField(default=True, help_text="Topshirgandan keyin natijani ko'rsatish.", verbose_name="natijani darhol ko'rsatish")),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='savollarni aralashtirish')),
                ('shuffle_choices', models.BooleanField(default=True, verbose_name='variantlarni aralashtirish')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='courses.course', verbose_name='kurs')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='courses.module', verbose_name='modul')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.test', verbose_name='test'),
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Davom etmoqda'), ('completed', 'Tugallangan'), ('timeout', 'Vaqt tugadi'), ('cancelled', 'Bekor qilingan')], default='in_progress', max_length=20, verbose_name='holat')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='boshlangan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='tugallangan')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name="yig'indi ball")),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='foiz')),
                ('is_passed', models.BooleanField(default=False, verbose_name="o'tdimi")),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL, verbose_name="o'quvchi")),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tests.test', verbose_name='test')),
            ],
            options={
                'verbose_name': 'Test urinishi',
                'verbose_name_plural': 'Test urinishlari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(blank=True, help_text="Tekshirilgandan keyin o'rnatiladi.", null=True, verbose_name="to'g'rimi")),
                ('answered_at', models.DateTimeField(auto_now=True, verbose_name='javob berilgan')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='tests.question', verbose_name='savol')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='selected_by', to='tests.choice', verbose_name='tanlangan variantlar')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.testattempt', verbose_name='urinish')),
            ],
            options={
                'verbose_name': "O'quvchi javobi",
                'verbose_name_plural': "O'quvchi javoblari",
            },
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['course'], name='idx_test_course'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['is_active'], name='idx_test_active'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['test', 'position'], name='idx_question_test_pos'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['test', 'student'], name='idx_attempt_test_student'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['status'], name='idx_attempt_status'),
        ),
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together={('test', 'student')},
        ),
        migrations.AddIndex(
            model_name='studentanswer',
            index=models.Index(fields=['attempt', 'question'], name='idx_answer_attempt_q'),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
