# Generated by Django 5.2.14 on 2026-08-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testattempt',
            unique_together=set(),
        ),
    ]
