# Generated by Django 5.2.14 on 2026-09-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_question_correct_text_question_passage_test_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='text_answer',
            field=models.CharField(blank=True, help_text="Matnli javob savollari uchun o'quvchining kiritgan matni.", max_length=500, verbose_name='matnli javob'),
        ),
    ]
