# Generated by Django 5.2.14 on 2026-08-23 14:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EssaySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_text', models.TextField(blank=True, default='', verbose_name='esse matni')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name="so'zlar soni")),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('ai_evaluated', 'AI baholadi'), ('pending_teacher', 'Ustoz tekshirishi kutilmoqda'), ('teacher_reviewed', 'Ustoz bahosi tayyor')], default='draft', max_length=20, verbose_name='holat')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='boshlangan')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='topshirilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_submissions', to=settings.AUTH_USER_MODEL, verbose_name="o'quvchi")),
            ],
            options={
                'verbose_name': 'Esse topshirish',
                'verbose_name_plural': 'Esse topshirishlar',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AIEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_scores', models.JSONField(default=dict, help_text="BMB mezonlari bo'yicha ballar.", verbose_name="mezon bo'yicha ballar (JSON)")),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='umumiy ball')),
                ('detected_errors', models.JSONField(default=list, verbose_name='aniqlangan xatolar (JSON)')),
                ('feedback_text', models.TextField(blank=True, default='', help_text='AI tomonidan berilgan umumiy tahlil va tavsiyalar.', verbose_name='AI feedback')),
                ('model_used', models.CharField(blank=True, default='gpt-4o-mini', max_length=50, verbose_name='AI model')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, verbose_name='baholangan')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_evaluation', to='essays.essaysubmission', verbose_name='esse topshirish')),
            ],
            options={
                'verbose_name': 'AI bahosi',
                'verbose_name_plural': 'AI baholari',
            },
        ),
        migrations.CreateModel(
            name='EssayTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='sarlavha')),
                ('description', models.TextField(help_text="O'quvchiga esse yozish uchun ko'rsatma.", verbose_name="tavsif / ko'rsatma")),
                ('category', models.CharField(choices=[('ona_tili', 'Ona tili'), ('adabiyot', 'Adabiyot'), ('tarix', 'Tarix'), ('umumiy', 'Umumiy')], default='ona_tili', max_length=20, verbose_name='kategoriya')),
                ('word_limit_min', models.PositiveIntegerField(default=150, verbose_name="minimal so'zlar soni")),
                ('word_limit_max', models.PositiveIntegerField(default=500, verbose_name="maksimal so'zlar soni")),
                ('time_limit_minutes', models.PositiveIntegerField(default=60, verbose_name='vaqt cheklovi (daqiqa)')),
                ('is_active', models.BooleanField(default=True, verbose_name='faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_essay_topics', to=settings.AUTH_USER_MODEL, verbose_name="yaratgan o'qituvchi")),
            ],
            options={
                'verbose_name': 'Esse mavzusi',
                'verbose_name_plural': 'Esse mavzulari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='essays.essaytopic', verbose_name='esse mavzusi'),
        ),
        migrations.CreateModel(
            name='TeacherReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_scores', models.JSONField(default=dict, help_text="O'qituvchi tomonidan belgilangan ballar.", verbose_name='ustoz mezon ballari (JSON)')),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='yakuniy ball')),
                ('teacher_comments', models.TextField(blank=True, default='', verbose_name='ustoz izohi')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='tekshirilgan')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_review', to='essays.essaysubmission', verbose_name='esse topshirish')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_reviews', to=settings.AUTH_USER_MODEL, verbose_name="tekshirgan o'qituvchi")),
            ],
            options={
                'verbose_name': 'Ustoz bahosi',
                'verbose_name_plural': 'Ustoz baholari',
            },
        ),
        migrations.AddIndex(
            model_name='essaysubmission',
            index=models.Index(fields=['student', 'status'], name='idx_essay_stu_status'),
        ),
        migrations.AddIndex(
            model_name='essaysubmission',
            index=models.Index(fields=['topic', 'status'], name='idx_essay_topic_status'),
        ),
    ]
