# Generated by Django 5.2.14 on 2026-08-24 17:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaysubmission',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='xatolik xabari'),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='baholangan'),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='max_score',
            field=models.PositiveSmallIntegerField(default=24, verbose_name='maksimal ball'),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='raw_result',
            field=models.JSONField(blank=True, default=dict, help_text="LLM dan kelgan to'liq JSON javob.", verbose_name='xom AI natijasi (JSON)'),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='xulosa'),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='total_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='umumiy ball'),
        ),
        migrations.AlterField(
            model_name='essaysubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('pending', 'Baholanmoqda'), ('graded', 'Baholandi'), ('error', 'Xatolik'), ('ai_evaluated', 'AI baholadi'), ('pending_teacher', 'Ustoz tekshirishi kutilmoqda'), ('teacher_reviewed', 'Ustoz bahosi tayyor')], default='draft', max_length=20, verbose_name='holat'),
        ),
        migrations.AlterField(
            model_name='essaysubmission',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='essays.essaytopic', verbose_name='esse mavzusi'),
        ),
        migrations.CreateModel(
            name='EssayCriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_id', models.PositiveSmallIntegerField(help_text='Mezon raqami (1-12).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='mezon raqami')),
                ('name', models.CharField(max_length=100, verbose_name='mezon nomi')),
                ('score', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)], verbose_name='ball')),
                ('reason', models.TextField(blank=True, default='', verbose_name='izoh')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='essays.essaysubmission', verbose_name='esse topshirish')),
            ],
            options={
                'verbose_name': 'Mezon bali',
                'verbose_name_plural': 'Mezon ballari',
                'ordering': ['criterion_id'],
                'indexes': [models.Index(fields=['submission', 'criterion_id'], name='idx_crit_sub_criterion')],
                'unique_together': {('submission', 'criterion_id')},
            },
        ),
    ]
