# Generated by Django 5.2.14 on 2026-08-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0002_essaysubmission_error_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayGradingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_hash', models.CharField(db_index=True, help_text='SHA-256 hash of normalized essay text.', max_length=64, unique=True, verbose_name='matn hash')),
                ('essay_text', models.TextField(help_text='Audit/debug uchun saqlanadi.', verbose_name='esse matni')),
                ('raw_result', models.JSONField(verbose_name='xom AI natijasi (JSON)')),
                ('total_score', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='umumiy ball')),
                ('max_score', models.PositiveSmallIntegerField(verbose_name='maksimal ball')),
                ('hit_count', models.PositiveIntegerField(default=1, help_text='Necha marta keshdan foydalanilgani.', verbose_name='ishlatilgan soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='oxirgi ishlatilgan')),
            ],
            options={
                'verbose_name': 'Baholash keshi',
                'verbose_name_plural': 'Baholash keshlari',
                'ordering': ['-hit_count', '-last_used_at'],
            },
        ),
    ]
