# Generated by Django 5.2.14 on 2026-08-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0003_essaygradingcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaysubmission',
            name='is_off_topic',
            field=models.BooleanField(default=False, help_text='Essa berilgan mavzuga mos yozilmaganmi.', verbose_name='mavzudan chetda'),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='topic_match_reason',
            field=models.TextField(blank=True, default='', help_text='LLM tomonidan berilgan izoh: nega mos yoki mos emas.', verbose_name='mavzu moslik sababi'),
        ),
    ]
