# Generated by Django 5.2.14 on 2026-08-25 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0004_essaysubmission_is_off_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaysubmission',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="O'qituvchi tomonidan tasdiqlangan yakuniy ball (agar mavjud bo'lsa).", max_digits=4, null=True, verbose_name="o'qituvchi yakuniy bali"),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='teacher_review_reason',
            field=models.TextField(blank=True, default='', help_text="O'quvchi nima uchun AI bahosiga rozi emasligini yozgan.", verbose_name="tekshirish so'rab sabab"),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='teacher_review_requested',
            field=models.BooleanField(default=False, help_text="O'quvchi AI bahosiga rozi bo'lmadi va ustozdan tekshirishni so'radi.", verbose_name="ustoz tekshiruvi so'ralgan"),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='teacher_review_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="tekshirish so'ralgan vaqt"),
        ),
        migrations.AlterField(
            model_name='teacherreview',
            name='final_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='yakuniy ball'),
        ),
    ]
