# Generated by Django 5.2.14 on 2026-09-08 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0009_essaysubmission_idx_essay_auto_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaytopic',
            name='grammar_strictness',
            field=models.PositiveSmallIntegerField(default=50, help_text='AI baholashda grammatika mezonining talabchanlik darajasi.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='grammatika talabchanligi (%)'),
        ),
        migrations.AddField(
            model_name='essaytopic',
            name='national_cert_scale',
            field=models.BooleanField(default=False, help_text="Yoqilganda — Milliy sertifikat ball shkalasi bo'yicha baholanadi.", verbose_name='Milliy sertifikat shkalasi'),
        ),
        migrations.AddField(
            model_name='essaytopic',
            name='sample_outline',
            field=models.TextField(blank=True, help_text="O'quvchiga ko'rsatiladigan namunaviy reja/kirish-ma'no-xulosa struktura.", verbose_name='namuna reja (outline)'),
        ),
    ]
