# Generated by Django 5.2.14 on 2026-09-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0010_essaytopic_grammar_strictness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaysubmission',
            name='improved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='yaxshilangan vaqti'),
        ),
        migrations.AddField(
            model_name='essaysubmission',
            name='improved_content',
            field=models.TextField(blank=True, default='', help_text='AI tomonidan yaratilgan yaxshilangan esse versiyasi (qayta yaratilishining oldini olish uchun saqlanadi).', verbose_name='AI yaxshilangan versiya'),
        ),
    ]
