# Generated by Django 6.1.1 on 2026-09-16 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0013_alter_teacherreview_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='essaysubmission',
            name='uniq_essay_active_draft',
        ),
    ]
