# Generated by Django 5.2.14 on 2026-09-19 15:46

from django.db import migrations, models


def backfill_pending_grading_started_at(apps, schema_editor):
    EssaySubmission = apps.get_model("essays", "EssaySubmission")
    EssaySubmission.objects.filter(
        status="pending",
        grading_started_at__isnull=True,
    ).update(grading_started_at=models.F("updated_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0014_remove_essaysubmission_uniq_essay_active_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaysubmission',
            name='grading_started_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='AI grading dispatch vaqti. PENDING holati cheksiz qolmasligi uchun ishlatiladi.', null=True, verbose_name='AI baholash boshlangan vaqt'),
        ),
        migrations.RunPython(
            backfill_pending_grading_started_at,
            migrations.RunPython.noop,
        ),
    ]
