# Generated by Django 5.2.14 on 2026-08-23 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('results', '0001_initial'),
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email')], default='telegram', max_length=20, verbose_name='kanal')),
                ('notification_type', models.CharField(choices=[('test_result', 'Test natijasi'), ('certificate', 'Sertifikat'), ('course_enrollment', 'Kursga yozilish'), ('reminder', 'Eslatma'), ('general', 'Umumiy')], default='general', max_length=30, verbose_name='xabar turi')),
                ('title', models.CharField(max_length=255, verbose_name='sarlavha')),
                ('message', models.TextField(verbose_name='xabar matni')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xatolik')], default='pending', max_length=20, verbose_name='holat')),
                ('external_id', models.CharField(blank=True, help_text='Telegram message_id yoki email Message-ID.', max_length=100, verbose_name='tashqi ID')),
                ('error_message', models.TextField(blank=True, verbose_name='xatolik xabari')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='yuborilgan')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='qabul qiluvchi')),
                ('related_certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='results.certificate', verbose_name="bog'langan sertifikat")),
                ('related_test_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='tests.testattempt', verbose_name="bog'langan test urinishi")),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient'], name='idx_notif_recipient'), models.Index(fields=['status'], name='idx_notif_status'), models.Index(fields=['channel', 'status'], name='idx_notif_chan_stat')],
            },
        ),
    ]
