# Generated by Django 5.2.14 on 2026-08-26 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, verbose_name='endpoint')),
                ('p256dh', models.CharField(max_length=255, verbose_name='p256dh key')),
                ('auth', models.CharField(max_length=255, verbose_name='auth key')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='user agent')),
                ('is_active', models.BooleanField(default=True, verbose_name='faolmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='oxirgi ishlatilgan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Push obuna',
                'verbose_name_plural': 'Push obunalar',
                'indexes': [models.Index(fields=['user', 'is_active'], name='idx_push_user_active')],
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
