# Generated by Django 5.2.14 on 2026-08-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_telegramauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramauthtoken',
            name='conversation_state',
            field=models.CharField(default='idle', help_text="Bot suhbat holati — ism/telefon to'plash", max_length=20),
        ),
        migrations.AddField(
            model_name='telegramauthtoken',
            name='full_name',
            field=models.CharField(blank=True, help_text="Foydalanuvchi to'liq ismi (bot orqali kiritilgan)", max_length=255),
        ),
        migrations.AddField(
            model_name='telegramauthtoken',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Telefon raqami (bot orqali kiritilgan)', max_length=20),
        ),
        migrations.AddField(
            model_name='telegramauthtoken',
            name='short_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='6 xonali kod — foydalanuvchi botdan olib saytga kiritadi', max_length=8),
        ),
    ]
