# Generated by Django 5.2.14 on 2026-09-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_telegramauthtoken_conversation_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramauthtoken',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
