# Generated by Django 6.1.1 on 2026-09-16 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0012_dedupe_active_drafts'),
        ('notifications', '0006_telegramauthtoken_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='related_essay_submission',
            field=models.ForeignKey(blank=True, help_text='Essay notification idempotency kaliti sifatida ishlatiladi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='essays.essaysubmission', verbose_name="bog'langan esse topshirish"),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('test_result', 'Test natijasi'), ('certificate', 'Sertifikat'), ('course_enrollment', 'Kursga yozilish'), ('reminder', 'Eslatma'), ('general', 'Umumiy'), ('essay_graded', 'Esse baholandi'), ('essay_review_request', "Esse tekshirish so'rovi")], default='general', max_length=30, verbose_name='xabar turi'),
        ),
    ]
